before_install: sudo apt-get install libzmq-dev

rvm:
  - 1.9.3
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-19mode

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-19mode # rbx seems to be losing exception messages o_O

notifications:
  irc: "irc.freenode.org#celluloid"
