rvm:
  - 1.9.3
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-19mode

matrix:
  allow_failures:
    # rbx seems to be losing exception messages o_O
    - rvm: rbx-19mode

notifications:
  irc: "irc.freenode.org#celluloid"
