before_install: sudo apt-get install libzmq-dev

rvm:
  - 1.9.3
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-19mode

matrix:
  allow_failures:
    - ruby-head
    - jruby-head
    # rbx seems to be losing exception messages o_O
    - rvm: rbx-19mode

notifications:
  irc: "irc.freenode.org#celluloid"
